---
title: "Complaints_Final"
author: "Jansen Baier"
date: "4/18/2022"
output: flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#importing data and run the standard stuff
library(tidyverse)
library(janitor) 
library(scales)
library(lubridate)
library(usmap)
library(ggplot2)
```
---
    
Row
-------------------------------------
    
### Chart 1 - Top 10 Companies Recieving Complaints
    
```{r}
top_10_complaint_companies <- complaints %>% 
  filter(company == "Experian Information Solutions Inc."|company == "TRANSUNION INTERMEDIATE HOLDINGS, INC."|company == "EQUIFAX, INC."|company == "CAPITAL ONE FINANCIAL CORPORATION"|company == "BANK OF AMERICA, NATIONAL ASSOCIATION"|company == "JPMORGAN CHASE & CO."|company == "CITIBANK, N.A."|company == "WELLS FARGO & COMPANY"|company == "SYNCHRONY FINANCIAL"|company == "PNC Bank N.A.")

ggplot(top_10_complaint_companies, aes(x = company)) +
  geom_bar(color = "#6ebcaa", fill = "#3eabda") +
  coord_flip()+
  scale_y_continuous(name = "Complaints", labels = scales::comma) +
  scale_x_discrete(name = "Companies") +
  labs(title = "Top 10 Comapnies By Number of Complaints", 
       subtitle = "",
       caption = "Consumer Complaint Database")

```
   
Row
-------------------------------------
    
### Chart 2 - Number of Complaints by State
    
```{r}
# I really tried to run this map, but it would not process, just too much data, it crashed R like 4 times. But I thought it was a cool idea so I left it in here
#plot_usmap(data = top_complaint_companies, values = "state", color = "red") + 
  #scale_fill_continuous(name = "Complaints", label = scales::comma) + 
  #theme(legend.position = "right")

library(dplyr)
library(stringr)
Renamed_complaints <- complaints %>% 
  rename_at(vars(starts_with("UNITED STATES MINOR OUTLYING ISLANDS")), 
              ~ str_replace(., "UNITED STATES MINOR OUTLYING ISLANDS", paste0("Outlying Islands", seq_along(.))))


ggplot(complaints, aes(x = state)) +
  geom_bar(width = .5, position = position_dodge(18), color = "#6ebcaa", fill = "#3eabda") +
  scale_y_continuous(name = "Complaints", labels = scales::comma) +
  scale_x_discrete(name = "Companies") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
  labs(title = "Top 10 Comapnies By Number of Complaints", 
       subtitle = "",
       caption = "Consumer Complaint Database")



```
    
### Chart 3 - Top 5 Complaints Throughout The Year

```{r}
```


